### ISSUE TITLE
Commands already defined when explaining several equations

### ISSUE THREAD

**Issue by joddm** [konstantin-morenko/latex-equation-explanation#1]
Hi, when I want to explain several equations on the same page/document I get the following error messages:

`LaTeX Error: Command \itemWidth already defined. [\item]
LaTeX Error: Command \leftSideWidth already defined. [\item]
LaTeX Error: Command \itemWidth already defined. [\item]
LaTeX Error: Command \leftSideWidth already defined. [\item]
LaTeX Error: Command \itemWidth already defined. [\item]
LaTeX Error: Command \leftSideWidth already defined. [\item]`

**Comment by konstantin-morenko** [comment]
Please, give the example of code you use to insert the equation.

**Comment by joddm** [comment]
`\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath, amsfonts, amssymb}
\usepackage{xcolor}
\usepackage{siunitx} % Celsius sign
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{eqexpl}
\eqexplSetIntro{where:} % set parenthesis in the left of the first item
\eqexplSetDelim{=} % set delimiter to "="

\begin{document}

\begin{equation} 
PPR = \frac{V_{a}(T_{f}-T_{a})}{1+0.3(T_{w}-T_{f})} 
\end{equation}

\begin{eqexpl}
\item{PPR}Icing Predictor, \si{\metre\celsius\per\second}
\item{$V_{a}$}Wind speed, \si{\metre\per\second}
\item{$T_{f}$}Freezing point of seawater, \si{\celsius}
\item{$T_{a}$}Air temperature, \si{\celsius}
\item{$T_{w}$}Sea water temperature, \si{\celsius}
\end{eqexpl}

\begin{equation}
Q_{f} = L_{fs}R_{i}
\end{equation}

\begin{eqexpl}
\item{$L_{fs}$}Latent heat of freezing of saline water, \si{\joule\per\kilo\gram}
\item{$R_{i}$}Ice accretion flux, \si{\kilo\gram\per\square\metre\second}
\end{eqexpl}

\begin{equation}
Q_{c} = h_{a}(T_{s}-T_{a})
\end{equation}

\begin{eqexpl}
\item{$h_{a}$}Heat transfer coefficient, \si{\watt\per\square\metre\celsius}
\item{$T_{s}$}Freezing temperature of brine, \si{\celsius}
\item{$T_{a}$}Air temperature at ship level, \si{\celsius}
\end{eqexpl}

\begin{equation}
Q_{d} = R_{w}c_{w}(T_{s}-T_{sp})
\end{equation}

\begin{eqexpl}
\item{$R_{w}$}Spray flux, \si{\kilo\gram\per\square\metre\second}
\item{$c_{w}$}Specific heat capacity of sea water, \SI{4000}{\joule\per\kilo\gram\celsius}
\item{$T_{s}$}Freezing temperature of brine, \si{\celsius}
\item{$T_{sp}$}Temperature of the spray at the position where icing occurs, \si{\celsius}
\end{eqexpl}

\end{document}`

**Comment by konstantin-morenko** [comment]
Thank you. I've fixed the bug, try new version.  Please, write me the result, because I have no opportunity to test the code right now.

**Comment by konstantin-morenko** [comment]
Code rewrited, this bug fixed.
